name: Build and publish

on:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  PRODUCTION_TRACK: ${{ (github.ref_type == 'tag' && !contains(github.ref_name, '-') && 'production') || (github.ref_type == 'branch' && github.ref_name == 'master' && 'staging') || '' }}

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            pppy/osu-server-spectator
          # generate Docker tags based on the following events/attributes
          # on tag event: tag using git tag, and as latest if the tag doesn't contain hyphens (pre-releases)
          # on push event: tag using git sha, branch name and as latest-dev
          tags: |
            type=raw,value=latest,enable=${{ github.ref_type == 'tag' && !contains(github.ref_name, '-') }}
            type=raw,value=latest-dev,enable=${{ github.ref_type == 'branch' && github.ref_name == 'master' }}
            type=raw,value=${{ github.ref_name }}
            type=raw,value=${{ github.sha }},enable=${{ github.ref_type == 'branch' }}
          flavor: |
            latest=false
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./osu.Server.Spectator
          file: ./osu.Server.Spectator/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  trigger_deploy:
    if: ${{ (github.ref_type == 'tag' && !contains(github.ref_name, '-')) || (github.ref_type == 'branch' && github.ref_name == 'master') }}
    runs-on: ubuntu-latest
    needs:
      - push_to_registry
    environment: ${{ (github.ref_type == 'tag' && !contains(github.ref_name, '-') && 'production') || 'staging' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.KUBERNETES_CONFIG_REPO_ACCESS_TOKEN }}
          repository: ppy/osu-kubernetes-config
          event-type: ${{ env.PRODUCTION_TRACK == 'staging' && 'dev-ppy-sh-deploy' || 'osu-server-spectator-deploy' }}
          client-payload: |-
            ${{ env.PRODUCTION_TRACK == 'staging' && format('{{ "values": {{ "osu-server-spectator": {{ "image": {{ "tag": "{0}" }} }} }} }}', github.sha) || format('{{ "dockerTag": "{0}" }}', github.ref_name) }}
      -
        name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ppy
          SENTRY_PROJECT: osu-server-spectator
          SENTRY_URL: https://sentry.ppy.sh/
        with:
          environment: ${{ env.PRODUCTION_TRACK }}
          version: osu-server-spectator@${{ github.ref_type == 'branch' && github.sha || github.ref_type == 'tag' && github.ref_name }}
