name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Unit testing
    steps:
      - uses: actions/checkout@v1
      - run: dotnet test
